---
openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Daniel-And-Moshe/WebDevelopment2021assignment3204415665_312257116/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /register:
    post:
      tags:
      - admins
      summary: Registerion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        "201":
          description: The Users Creadet Successful
        "400":
          description: wrong Input Parameters
components:
  schemas:
    user:
      type: object
      properties:
        Username:
          maxLength: 8
          minLength: 3
          type: string
          description: Name Of The User
        firstname:
          type: string
          description: User's First Name
        lastname:
          type: string
          description: User's Last Name
        country:
          type: string
          description: User's Country
        password:
          maxLength: 10
          minLength: 5
          type: string
          description: User Password
          format: password
        confirmationpassword:
          type: string
          description: User Password Again
          format: password
        email:
          type: string
          description: User Email Address
          format: email
        linkForProfilePic:
          type: string
          description: Link For User Picture
          format: url
